### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers.
The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by edangonz** [comment]
Attached is a 
[Report.docx](https://github.com/jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II/files/7885925/Report.docx)
document with report on new functionality implementation.

**Comment by jose598** [comment]
Hi @edangonz, I was taking a look of the attached document, whole description detailed is good however it's important for me to know how you are considering the prima base calculation. So, Please send me back the doc with this specification. 
Also, I want to know who is the analyst, developer and tester. 


Greeting,

**Comment by edangonz** [comment]
Thank you for corrections, I attach the document again.
[Report.docx](https://github.com/jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II/files/7886056/Report.docx)

**Comment by jose598** [comment]
Ok @edangonz. All looks nice. 
All of you can start working on it.

**Comment by jeffpr11** [comment]
Hi @jose598 , clear something for us when the new business rule says $50 must be decreased to the base premium for each one, does it means a decrease $50 for each year of the difference between 60 and the customer's age right? because the base price is $500 and these new rule comes after 
-$100 if age is between 45 and 64
-$200 if is women or is married
So, when customer is 50yo calculator will try to decrease $500 to an already base price decreased in $300...

**Comment by jose598** [comment]
I think that the base price is 600 but even when the base price is 500, if she is 50 and married the discount applied for her is 300 before calculating this new issue, then it will be decreased maximum 100, it means that the result is over 0, don't care how much she will pay, just that the balance is over 0.

**Comment by jeffpr11** [comment]
Issue categorizada, @edangonz will be analyst, @GeorgHenriquez will perform the tests and I am going to develop the solution.

**Comment by jeffpr11** [comment]
https://github.com/jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II/blob/779a8083e3dec73aed228e215fb71014c3beacd5/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L60-L68

**Comment by jose598** [comment]
Everything sounds good. Please continue with test process.

**Comment by GeorgHenriquez** [comment]
Here is the test plan @jose598 
[Test Plan.docx](https://github.com/jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II/files/7907446/Test.Plan.docx)

**Comment by jose598** [comment]
@GeorgHenriquez  I don't understand your test plan and how your estimate the expecting result and actual result. Also, I don't know where is the test for the two cases/rules that you did.

**Comment by GeorgHenriquez** [comment]
Hello @jose598, I am attach the updated test plan. Also, the tests for the two new test cases are 03-04 and 03-07.
[Test Plan.docx](https://github.com/jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II/files/7917058/Test.Plan.docx)

**Comment by jose598** [comment]
Ok now I got it. 

I already approved your changes, thank you. 
Please close the issue.

**Comment by jeffpr11** [comment]
@jose598
The main branch is totally up to date with the new release of code for this issue.
You can download the repository, run CarInsurance.java and you will get the value result of calculate this cases:
50yo female married with license
65yo female not married with license

Here you can replace the inputs:
https://github.com/jeffpr11/ISII-WORKSHOPS-MIS_MASCOTAS_II/blob/b81525b935389418a32ab8401df5fce408704ceb/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L25-L30

**Comment by jeffpr11** [comment]
![image](https://user-images.githubusercontent.com/55856634/150616918-794e654f-b627-4d4c-89bf-7bfe9fb535ea.png)
